### PR TITLE
instead of using CWD use '.' for deploying the root dir

### PR DESCRIPTION
**Pull request by rybit**

### CODE REVIEW

**Comment by calavera** [comment]
why? This is not portable and it won't work on Windows.

**Comment by rybit** [comment]
Otherwise you record the current directory ~ which means that if you move that dir it is going to break.

**Comment by biilmann** [comment]
What would be the equivalent on windows? Actually hoped the `.` might work, we might need to make the empty string work otherwise

**Comment by calavera** [comment]
> which means that if you move that dir it is going to break.

Sorry, I'm not familiar with this implementation. Where are we recording that path? is the path absolute?

**Comment by rybit** [comment]
yeah it used to record the cwd in the .netlify file

**Comment by biilmann** [comment]
We're storing the path in the `.netlify` config file. The issue is when there's no path specified and we fall back to `process.cwd()` and that ends up being an absolute path (where obviously `.netlify` ought to store a relative path.

**Comment by calavera** [comment]
Store a relative path to the `.netlify` file and expand when it's necessary. Don't store anything if `result.path` is empty.

**Comment by rybit** [comment]
that means that each time you deploy you'll be asked what dir you want to deploy.

**Pull request closed without merging**
